//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleMenuMasterDBEntities : DbContext
    {
        public SampleMenuMasterDBEntities()
            : base("name=SampleMenuMasterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblLogin> tblLogins { get; set; }
        public DbSet<tblMainMenu> tblMainMenus { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblSubMenu> tblSubMenus { get; set; }
    }
}
